CREATE INDEX "accounts_user_id_idx" ON "accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "users_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_status_idx" ON "users" USING btree ("status");--> statement-breakpoint
CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "wallet_transactions_user_id_idx" ON "wallet_transactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "wallet_transactions_wallet_id_idx" ON "wallet_transactions" USING btree ("wallet_id");--> statement-breakpoint
CREATE INDEX "wallet_transactions_created_at_idx" ON "wallet_transactions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "wallet_transactions_status_idx" ON "wallet_transactions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "wallets_created_at_idx" ON "wallets" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "funding_requests_user_id_idx" ON "funding_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "funding_requests_status_idx" ON "funding_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "funding_requests_created_at_idx" ON "funding_requests" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "draw_entries_draw_id_idx" ON "draw_entries" USING btree ("draw_id");--> statement-breakpoint
CREATE INDEX "draw_entries_draw_prize_id_idx" ON "draw_entries" USING btree ("draw_prize_id");--> statement-breakpoint
CREATE INDEX "draw_entries_user_id_idx" ON "draw_entries" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "draw_entries_created_at_idx" ON "draw_entries" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "draw_prizes_draw_id_idx" ON "draw_prizes" USING btree ("draw_id");--> statement-breakpoint
CREATE INDEX "draw_prizes_urgency_status_idx" ON "draw_prizes" USING btree ("urgency_status");--> statement-breakpoint
CREATE INDEX "draw_prizes_end_time_idx" ON "draw_prizes" USING btree ("end_time");--> statement-breakpoint
CREATE INDEX "draw_prizes_created_at_idx" ON "draw_prizes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "draws_slot_number_idx" ON "draws" USING btree ("slot_number");--> statement-breakpoint
CREATE INDEX "draws_status_idx" ON "draws" USING btree ("status");--> statement-breakpoint
CREATE INDEX "draws_start_time_idx" ON "draws" USING btree ("start_time");--> statement-breakpoint
CREATE INDEX "draws_created_at_idx" ON "draws" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "winners_user_id_idx" ON "winners" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "winners_draw_prize_id_idx" ON "winners" USING btree ("draw_prize_id");--> statement-breakpoint
CREATE INDEX "winners_announced_at_idx" ON "winners" USING btree ("announced_at");--> statement-breakpoint
CREATE INDEX "spin_history_user_id_idx" ON "spin_history" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "spin_history_reward_id_idx" ON "spin_history" USING btree ("reward_id");--> statement-breakpoint
CREATE INDEX "spin_history_spin_date_idx" ON "spin_history" USING btree ("spin_date");--> statement-breakpoint
CREATE INDEX "quiz_attempts_user_id_idx" ON "quiz_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "quiz_attempts_quiz_id_idx" ON "quiz_attempts" USING btree ("quiz_id");--> statement-breakpoint
CREATE INDEX "quiz_attempts_attempted_at_idx" ON "quiz_attempts" USING btree ("attempted_at");--> statement-breakpoint
CREATE INDEX "quizzes_is_active_idx" ON "quizzes" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "quizzes_active_from_idx" ON "quizzes" USING btree ("active_from");--> statement-breakpoint
CREATE INDEX "quizzes_scheduled_at_idx" ON "quizzes" USING btree ("scheduled_at");--> statement-breakpoint
CREATE INDEX "quizzes_created_at_idx" ON "quizzes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "notifications_is_read_idx" ON "notifications" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "notifications_created_at_idx" ON "notifications" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "referrals_referrer_user_id_idx" ON "referrals" USING btree ("referrer_user_id");--> statement-breakpoint
CREATE INDEX "referrals_status_idx" ON "referrals" USING btree ("status");--> statement-breakpoint
CREATE INDEX "referrals_created_at_idx" ON "referrals" USING btree ("created_at");